/* 
  THIS FILE IMPORTS AND EXPORTS ALL SHARED ASSETS 
  IT IS IMPORTANT FOR DEBUGGING UNUSED ASSET 
  AS JUST REMOVING A CURRENTLY USED EXPORT WOULD CAUSE THE APP TO BREAK 
*/
import LendsqrLogo from './lendsqr.svg'

export {
  LendsqrLogo
}
